---
#- name: Rancher 2 Kubernetes Nodes - workers
#  hosts: rancher-2-workers
#  roles:
#    - s2m.rke.common
#    - geerlingguy.firewall

#- name: Rancher 2 Kubernetes Nodes-cp
#  hosts: rancher-2-controlplane
#  roles:
#    - s2m.rke.common
#    - geerlingguy.firewall

- name: Rancher 2 Kubernetes Nodes - Admin Platform
  hosts: rancher-2-kubernetes-nodes
  roles:
    - s2m.rke.common
    - geerlingguy.firewall
