apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres-postgresql-ha-pgpool
  labels:
    app: postgres # Defines app to create service for
spec:
  ports:
    - port: 5432 # Sets the port to run the postgres application
  selector:
    app: postgres

