apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{ include "keycloak.labels" . | nindent 4 }}
data:
  # keycloak
  KEYCLOAK_LOGLEVEL: "{{ .Values.keycloak.logLevel }}"
  PROXY_ADDRESS_FORWARDING: "{{ .Values.keycloak.proxyAddressForwarding }}"
  KEYCLOAK_USER: "{{ .Values.keycloak.user }}"
  KEYCLOAK_FRONTEND_URL: "{{ .Values.keycloak.frontendUrl }}"
  # topic
  ADMIN_EVENT_TOPIC: "{{ .Values.topic.adminEvent }}"
  USER_EVENT_TOPIC: "{{ .Values.topic.userEvent }}"
  BRUTE_FORCE_TOPIC: "{{ .Values.topic.brutForce }}"
  # kafka
  BOOTSTRAP_SERVERS: "{{ .Values.kafka.bootstrapServers }}"
  SCHEMA_REGISTRY_ENDPOINT: "{{ .Values.kafka.schemaRegistryEp }}"
  PRODUCER_ACKS: "{{ .Values.kafka.producerAcks }}"
  # db
  DB_VENDOR: "{{ .Values.db.vendor }}"
  DB_ADDR: "{{ .Release.Name }}-mysql"
  DB_PORT: "{{ .Values.db.port }}"
  JDBC_PARAMS: "{{ .Values.db.params }}"
  DB_USER: "{{ .Values.db.user }}"
  DB_DATABASE: "{{ .Values.db.database }}"
