apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-init-keycloak
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config/*").AsConfig | nindent 2 }}
