apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
type: Opaque
data:
  databasePassword: "{{ .Values.db.password }}"
  keycloakPassword: "{{ .Values.keycloak.password }}"  
