apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: testtwo
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test
    namespace: default
    resourceVersion: "15385"
    uid: 41774f6c-5a75-42a0-a1be-45e6d2521d6d
  csi:
    driver: driver.longhorn.io
    fsType: xfs
    volumeAttributes:
      diskSelector: ""
      nodeSelector: ""
      numberOfReplicas: "1"
      staleReplicaTimeout: "20"
    volumeHandle: test
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
